In [37]:
import numpy as np

a = np.arange(256).reshape((16,16))
# a

### 🎩 Fancy Indexing in NumPy
Fancy indexing is a NumPy feature that allows you to index arrays using arrays (or lists) of integers or booleans instead of slices.

```python
a[[0, 11, 2]]  # 0th row, 12th row, 3rd row
```


In [9]:
#fancy indexing: Fancy indexing is a NumPy feature that 
# allows you to index arrays using arrays (or lists) of 
# integers or booleans instead of just slices (:).
a[[0,11,2]] #0th row, 12th row, third row



array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [ 32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
         45,  46,  47]])

In [12]:
a[[11,7,13,1,14]]

array([[176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
        125, 126, 127],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [ 16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239]])

In [26]:
#Boolean Indexing
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[62,  1,  7, 43],
       [35,  6, 82, 76],
       [33, 59, 88, 29],
       [85, 93, 90, 63],
       [25, 72, 13, 82],
       [60, 39, 14, 66]], dtype=int32)

In [19]:
#Boolean Masking(loosely)
b > 50

array([[ True, False, False,  True],
       [False, False, False,  True],
       [ True, False, False, False],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
#Boolean Indexing
b[b > 50]

array([62, 82, 76, 59, 88, 85, 93, 90, 63, 72, 82, 60, 66], dtype=int32)

In [29]:
#find evens using Boolean indexing
b[b %2 == 0]

array([62,  6, 82, 76, 88, 90, 72, 82, 60, 14, 66], dtype=int32)

In [38]:
#Find all numbers greater than 50 and even
b[(b > 50) & (b % 2 == 0)] # both the experssion are boolean, that's why bitwise AND(&)

array([62, 82, 76, 88, 90, 72, 82, 60, 66], dtype=int32)

In [41]:
#all numbers not divisible by 7
a[~(a % 7 == 0) & (a < 50)]

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18, 19,
       20, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 34, 36, 37, 38, 39,
       40, 41, 43, 44, 45, 46, 47, 48])