# 📏 NumPy Broadcasting Rules

Broadcasting in NumPy lets you perform operations on arrays of different shapes — **without copying data**. But it only works when **certain rules** are followed.

---

## ✅ The Broadcasting Rule

To broadcast two arrays **A** and **B**:

1. Start from the **trailing dimensions** (rightmost).
2. Compare dimensions from **right to left**.
3. Two dimensions are **compatible** if:
   - They are **equal**, OR
   - One of them is **1**

If **all compared dimensions** are compatible, broadcasting succeeds.

---

## 📚 Example 1: Can Broadcast ✅

```
A.shape = (4, 3, 2)
B.shape =       (3, 1)
```

Pad B to match shape length:

```
A: (4, 3, 2)
B: (1, 3, 1)
```

Comparison:

- 2 vs 1 → ✅
- 3 vs 3 → ✅
- 4 vs 1 → ✅

✅ Broadcasting successful!  
🧾 Result shape: `(4, 3, 2)`

---

## 📚 Example 2: Cannot Broadcast ❌

```
A.shape = (5, 4)
B.shape = (3, 1)
```

Comparison:

- 4 vs 1 → ✅
- 5 vs 3 → ❌

❌ Broadcasting fails here.

---

## 🧠 TL;DR — Compatibility Rule

```
For each dimension (right to left):
  if dim1 == dim2 → OK
  if dim1 == 1    → OK (stretch dim1)
  if dim2 == 1    → OK (stretch dim2)
  else            → ERROR
```

---

## 🔍 Result Shape Rule

NumPy computes the result shape by:

- Keeping the maximum dimension size if compatible.
- Stretching the 1-sized dimensions.
- Raising an error if incompatible.

---

## 🧪 Try It in Code

```python
import numpy as np

a = np.empty((5, 1, 3))
b = np.empty((  4, 1))

result = a + b  # Will this work?

print(result.shape)
```

---

Broadcast 

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic oeprations.

The smaller array is 'broadcast' across the larger array so that they have compatible shapes.

Broadcasting Rules

1. Make the two arrays have the same number of dimensions.
  => If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

2. Make Each dimension of the two arrays the same size
  =>If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
  =>If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised

Note: last dimesions of smaller and bigger arrays should match to broadcast

In [13]:
import numpy as np

In [14]:
#same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)

print(a + b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [15]:
#same shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a, end="\n\n")
print(b, end="\n\n")

print(a + b)

[[0 1 2]
 [3 4 5]]

[[0 1 2]]

[[0 2 4]
 [3 5 7]]


In [18]:
#Examples
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)
print(a + b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)
print(a + b) #Error: last dimesions are not equal. i.e. 3 != 4

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
a = np.arange(12).reshape(3, 4)
b = np.arange(4).reshape(4, 1)

print(a + b) #last dimensions are not equal, 1 != 4

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [23]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)
print(a + b)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [24]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

#ye dono na ho paayenge broadcast
print(a + b)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [25]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a + b)

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 