In [1]:
import numpy as np


a1 = np.arange(11)
print(a1)

#indexing

print(a1[-1])


a2 = np.arange(12).reshape(3, 4)
print(a2)


print(a2[1,2])

print(a2[2, 3])
print(a2[1,0])

a3 = np.arange(8).reshape(2,2,2)
print(a3)

print(a3[1, 0, 1])
print(a3[1][0][1])
print(a3[0, 0, 0])
print(a3[1, 1, 0])


#Slicing: fetch multiple items

# 1-D numpy ndarray
a1_slice = a1[2 : 5]
print(a1_slice)
a1_slice = a1[2 : 5 : 2]
print(a1_slice)

a2_slice = a2[0, :] #0-> first row, : -> all columns
print(a2_slice)

[ 0  1  2  3  4  5  6  7  8  9 10]
10
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
11
4
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
5
5
0
6
[2 3 4]
[2 4]
[0 1 2 3]


In [ ]:
#Slicing 2-D array
#Slice is a view not a copy. Any change to slice will reflect in original array
#syntax: arr[start:stop:step] step is optional
a2_slice1 = a2[2, :] # first row all column, a2[2 : :] is also acceptable
print(a2_slice1)

a2_column_slice = a2[:, 0] # all rows, first column
a2_column_slice

[ 8  9 10 11]


array([0, 4, 8])

In [ ]:
#slicing a slice of a 2-D array
a2_slice_slice = a2[2: :, 1 : 3]
a2_slice_slice = a2_slice1[1:3]
a2_slice_slice

array([[ 9, 10]])

In [19]:
#slice of a slice of all rows and second column
a2_rows_slice = a2[:, 0, 0 : 1]
a2_rows_slice

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [40]:
arr = a2
print(arr)

arr.ndim
arr.shape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(3, 4)

In [43]:
arr[1, :] # second row, all columns
arr[2, 0 : 3] #third row(2), first to third element(0 : 3)

#Note: keep row number and slice separated by comma(mere understanding)

array([ 8,  9, 10])

In [ ]:
arr[:, 0] # all rows, column 1
arr[:, 1:3] # all rows, column second and third(third column idx is 3)

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [54]:
print(arr[0,0])

0


In [56]:
arr = arr.reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [63]:
print(arr[0,0,0])
print(arr[0,1,2]) #first row ke second row ka third element
print(arr[0,1,1])
print(arr[0,0,2])

print(arr[1,1,1])
print(arr[1,0,0])

0
5
4
2
10
6


In [ ]:
a1[2 : 5]
print(a1[-1:]) # last row last column

[10]


In [74]:
arr[0, :]
arr[:, 1]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [76]:
arr = arr.reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
arr = np.arange(56).reshape(7, 8)
print(arr)
arr[:, 2] #all rows, third column
arr[1:, 1:3]


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]]


array([[ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50]])

In [141]:
# print(arr[2:4, 2:4])
# print(arr[: : 2, ::2])
# print(arr[: : 2, : : 3])
print(arr[0: :2,  2: :2])
print(arr[: : 6, 1::5])
print(arr[3::6, 0: 7 : 6])
print(arr[3, 0::6])

[[ 2  4  6]
 [18 20 22]
 [34 36 38]
 [50 52 54]]
[[ 1  6]
 [49 54]]
[[24 30]]
[24 30]


In [146]:
temp = np.arange(12).reshape(3, 4)
temp
print(temp[1::3, 0::3])
print(temp[1, ::3])
print(temp[0:2, 1:])

[[4 7]]
[4 7]
[[1 2 3]
 [5 6 7]]
