In [4]:
import numpy as np
arr = np.arange(11)

In [6]:
for i in range(len(arr)):
  print(arr[i], end=" ")

0 1 2 3 4 5 6 7 8 9 10 

In [8]:
a2 = np.arange(12).reshape(3,4)
for i in range(a2.shape[0]):
  for j in range(a2.shape[1]):
    print(a2[i][j], end=" ")
  

0 1 2 3 4 5 6 7 8 9 10 11 

In [9]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [16]:
print(np.transpose(a2))
a2.T

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [10]:
a3 = np.arange(27).reshape(3,3,3)
for i in a3:
  print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [12]:
for i in np.nditer(a3):
  print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [18]:
#ravel: flatten an ndarray
print(a2.ravel())
print(a3.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
