
# 🔢 `numpy.sort()` – Fast & Flexible Sorting in NumPy

```python
numpy.sort(a, axis=-1, kind='quicksort', order=None)
```

## 📌 Parameters:

- **`a`** : *array_like*  
  The input array to sort.

- **`axis`** : *int or None*, default = `-1`  
  Axis to sort along. Use `None` to flatten before sorting.

- **`kind`** : *{'quicksort', 'mergesort', 'heapsort', 'stable'}*  
  Sorting algorithm to use:
  - `'quicksort'` – fast but unstable  
  - `'mergesort'` – stable  
  - `'heapsort'` – memory-efficient  
  - `'stable'` – guaranteed stability (since NumPy 1.15)

- **`order`** : *str or list of str*, optional  
  For sorting structured arrays by field names.


In [10]:
#sort
import numpy as np



a = np.random.randint(1,100,15)
print(f'Original Array\n {a}')
print(f'Sorted\n {np.sort(a)}')
print(f'Reverse Sorted\n {np.sort(a)[::-1]}')

Original Array
 [12 81 88 53 54 45 49  8 39 87 22  8 44 41 20]
Sorted
 [ 8  8 12 20 22 39 41 44 45 49 53 54 81 87 88]
Reverse Sorted
 [88 87 81 54 53 49 45 44 41 39 22 20 12  8  8]


In [11]:
b = np.random.randint(1,100,24).reshape(6,4)
print(f'Original Array\n {b}')
print(f'Sorted\n {np.sort(b)}') #Default sort element within each row
print(np.sort(b, axis=0)) #column wise sorting
print(np.sort(b, axis=1)) #row wise sorting

Original Array
 [[76  3 96 20]
 [60 87 75 71]
 [ 3 35  7  9]
 [22 62 61  8]
 [89 88 33 92]
 [49 14 61 46]]
Sorted
 [[ 3 20 76 96]
 [60 71 75 87]
 [ 3  7  9 35]
 [ 8 22 61 62]
 [33 88 89 92]
 [14 46 49 61]]
[[ 3  3  7  8]
 [22 14 33  9]
 [49 35 61 20]
 [60 62 61 46]
 [76 87 75 71]
 [89 88 96 92]]
[[ 3 20 76 96]
 [60 71 75 87]
 [ 3  7  9 35]
 [ 8 22 61 62]
 [33 88 89 92]
 [14 46 49 61]]


In [12]:
# Reverse sorting
print(np.sort(b)[::-1])

[[14 46 49 61]
 [33 88 89 92]
 [ 8 22 61 62]
 [ 3  7  9 35]
 [60 71 75 87]
 [ 3 20 76 96]]


In [17]:
arr = input().strip().split(' ')
arr = np.array(arr, dtype=float)
print(type(arr))
print(arr)
print(np.sort(arr)[::-1])

<class 'numpy.ndarray'>
[ 1.  2.  3. 45.]
[45.  3.  2.  1.]
